### ISSUE TITLE
Improved Blizzard

### ISSUE THREAD

**Issue by d87** [rgd87/LibClassicDurations#23]
Imp Blizzard doesn't generate SPELL_AURA_APPLIED/REMOVED events in combat log.
I'm trying to use SPELL_DAMAGE event instead in this branch: https://github.com/rgd87/LibClassicDurations/commits/ImpBlizzard

People report it's not working.
I need to confirm:
1) Whether blizzard makes SPELL_DAMAGE or SPELL_PERIODIC_DAMAGE. On Live it's SD
2) If first SPELL_DAMAGE happens before the UNIT_AURA event that adds Chilled aura
3) Is it really not working?

**Comment by Witnesscm** [comment]
>76011.658 COMBAT_LOG_EVENT_UNFILTERED SPELL_CAST_SUCCESS Blizzard
76011.908 COMBAT_LOG_EVENT_UNFILTERED SPELL_AURA_APPLIED Blizzard DEBUFF
76011.908 UNIT_AURA target //Blizzard (a hidden aura)
76012.932 COMBAT_LOG_EVENT_UNFILTERED SPELL_PERIODIC_DAMAGE Blizzard
76013.544 UNIT_AURA target //Chilled (gained)
76013.924 COMBAT_LOG_EVENT_UNFILTERED SPELL_PERIODIC_DAMAGE Blizzard  
76014.354 UNIT_AURA target //Chilled
76014.924 COMBAT_LOG_EVENT_UNFILTERED SPELL_PERIODIC_DAMAGE Blizzard 
76015.567 UNIT_AURA target //Chilled
76015.937 COMBAT_LOG_EVENT_UNFILTERED SPELL_PERIODIC_DAMAGE Blizzard 
76016.377 UNIT_AURA target //Chilled
76016.937 COMBAT_LOG_EVENT_UNFILTERED SPELL_PERIODIC_DAMAGE Blizzard 
76017.581 UNIT_AURA target //Chilled
76017.931 COMBAT_LOG_EVENT_UNFILTERED SPELL_PERIODIC_DAMAGE Blizzard
76018.402 UNIT_AURA target //Chilled
76018.922 COMBAT_LOG_EVENT_UNFILTERED SPELL_PERIODIC_DAMAGE Blizzard
76019.622 UNIT_AURA target //Chilled
76019.932 COMBAT_LOG_EVENT_UNFILTERED SPELL_PERIODIC_DAMAGE Blizzard
76019.932 COMBAT_LOG_EVENT_UNFILTERED SPELL_AURA_REMOVED Blizzard DEBUFF
76019.932 UNIT_AURA target //Blizzard
76020.415 UNIT_AURA target //Chilled
76024.890 UNIT_AURA target //Chilled (faded)

I am trying to print COMBAT_LOG_EVENT_UNFILTERED and UNIT_AURA events.

1. Blizzard makes SPELL_PERIODIC_DAMAGE
2. SPELL_PERIODIC_DAMAGE happens about 0.4s - 0.6s before the UNIT_AURA event
3. It's still not working, because Improved Blizzard and Frost Armor has the same aura name (Chilled)

**Comment by d87** [comment]
Oh, thanks. I would've never guessed they have the same spell name.
Can you confirm that it works now after https://github.com/rgd87/LibClassicDurations/commit/527c779e0657517ff6dfbbd19da187082d9d140d ?

**Comment by Witnesscm** [comment]
![pic1](https://user-images.githubusercontent.com/23260622/66268313-c6bf8e80-e86e-11e9-9eea-3a69f333e5b6.png)
Thanks. It works now but still has some problem.

1. The Frost/Ice Armor (Chilled) duration was refreshed wrongly when I cast Blizzard
2. The Improved Blizzard (Chilled) duration ends early, because aura event happens after damage event about 0.5 sec.
Maybe can change the Imp Blizzard duration from 4.5 sec to 5 sec ?

**Comment by d87** [comment]
>The Frost/Ice Armor (Chilled) duration was refreshed wrongly when I cast Blizzard

Ok, I fixed it a little differently right now and managed to separate them

>Maybe can change the Imp Blizzard duration from 4.5 sec to 5 sec ?

Done

So try it again please

**Comment by Witnesscm** [comment]
Now it works very well. Thanks!
