### ISSUE TITLE
latest WA alpha breaks libclassicdrurations across multiple addons

### ISSUE THREAD

**Issue by gobacktogo** [rgd87/LibClassicDurations#35]
hey,

so far i've been using elvui and a dev version of plater to show enemy buffs. this works flawlessly, thanks to your nice library.

however, the latest weakaura alpha now also supports this feature of libclassicdurations. unfortunately, it only seems to work when WA is the only addon making use of this feature.

to explain in more detail: 
- only WA alpha enabled: enemy buffs show up.
- only elvui and plater dev version enabled: both addons show enemy buffs just fine.
- WA alpha together with elvui: both addons stop showing enemy buffs.
- WA alpha together with plater dev: both addons stop showing buffs.

let me know if i can test anything or if you need further feedback.
thanks!

**Comment by d87** [comment]
Install these two
https://www.curseforge.com/wow/addons/bugsack
https://www.curseforge.com/wow/addons/bug-grabber
Check if you have any errors when it doesn't work

Open issue for WA, tho i already PMd Buds

And as far as i can see Plater has got a bug here https://github.com/Tercioo/Plater-Nameplates-Classic/commit/0c29cc41063b29af7ce2ad18feb89fea0784d1e0#diff-b849b38f748aa9dd75f79bbc64b62c82R77

**Comment by cont1nuity** [comment]
Hi @d87,
thanks for the reply.

I did not implement the callback, as we're gathering the buff information later with LCD:UnitAura calls.
Plater does not directly use the unit_aura events either, but updates frequently. (Can be seen as a flaw, but it works that way since Tercioo implemented that.)

The issue seems to arise when WA is enabled, so I assume it is an issue on their end.
If not: I'll gladly fix anything.

**Comment by cont1nuity** [comment]
Update:
Issue seems to be caused by outdated LibClassicDuration in ElvUI (v34) and Plater (v31) vs. WeakAuras (v35).
As WA loads after Plater (usually by alphabetical order), the Lib is loaded in the newer version and I assume that the registration is lost in this process.

Is there anything we can do to prevent this from happening, except anew registration of the events?

**Comment by cont1nuity** [comment]
Thanks for the fast fix!
Plater-Classic release is out with the latest modifications.
