### ISSUE TITLE
Incorrect Sunder Armor duration refresh

### ISSUE THREAD

**Issue by Ravidge** [rgd87/LibClassicDurations#51]
Whenever a sunder armor cast is **dodged** or **parried** (those are the two cases I've confirmed at least) this library/addon will incorrectly refresh the duration timer. Causing a mismatch between what this library/addon displays, and the actual (hidden) internal timer of the debuff.

If a warrior is assigned to refresh sunder on bosses, they will fail to do so in ~1/15 fights (6.5% dodge). And the debuff will simply time-out while this person assumed it was properly refreshed.

I believe that you created a early workaround for some duration refresh issues, but if it's possible, please make it even more robust and reliable!
This problem is occurring more and more often as the number of raids increases (more fights per week).

I wish I could do more, but I'm not a coder and I know nothing about addons... I did my best in tracking down this problem, and I hope it's useful feedback.

**Comment by d87** [comment]
Ok, done

**Comment by wardz** [comment]
Might want to implement `rollbackMisses` for Winter's Chill aswell since it's possible for the WC debuff itself to resist even though Frostbolt was not resisted. Right now WC is still refreshed on aura resist. Might be the same for Shadow Weaving aswell but I haven't tested that one.

**Comment by d87** [comment]
Are you sure it doesn't work? WC and Shadow Weaving already have another type of hack for resists. Unlike sunder It's based on the assumption that SPELL_DAMAGE (from which they refresh) comes always after the aura application/resist event. And if there was a resist then it doesn't refresh.
I don't have neither priest nor mage to confirm the actual order of the events

**Comment by wardz** [comment]
Yes im sure. Here's the following events when this issue happens:


- SPELL_CAST_START - Frostbolt
- SPELL_CAST_SUCCESS - Frostbolt
- SPELL_AURA_REFRESH - Frostbolt
- SPELL_DAMAGE - Frostbolt
- SPELL_MISSED - Winter's Chill

![th](https://user-images.githubusercontent.com/10900212/77960163-19d34500-72d8-11ea-875b-3348c8e03cff.png)

The hack you're talking about seems to currently only work when Frostbolt itself is resisted.

**Comment by d87** [comment]
Ok, switched everything to rollbacks

**Comment by wardz** [comment]
Tested it now, it seems the debuff(s) fail to refresh due to 2 issues:

**1)**
https://github.com/rgd87/LibClassicDurations/blob/6fdf2575fb11a668bb23207ed0201e931d789fb3/core.lua#L519-L520

This part will almost never run. I printed the results of `now - timestamp` and it seems it always ranges from ~4 to ~29 for me (playing with a 37ms latency). So im guessing this threshold is either supposed to be in milliseconds, or it's calculating how long the debuff has been active on the target instead of time between `SPELL_DAMAGE` and `SPELL_MISSED`.
  
**2)**
https://github.com/rgd87/LibClassicDurations/blob/6fdf2575fb11a668bb23207ed0201e931d789fb3/core.lua#L509-L513

This part will never run for Winter's Chill or Shadow Weaving resists since the table for WC/SW doesn't exist. Quickly adding something like this seem to fix it, even for Cone of Cold/Frost Nova.
```lua
-- Winter's Chill = Frostbolt
lib.indirectRefreshSpells[GetSpellInfo(12579)] = lib.indirectRefreshSpells[GetSpellInfo(25304)]
```

After changes to these issues it works perfectly, atleast for WC. I haven't tested SW but I dont see why it'd be any different.

**Comment by d87** [comment]
1) GetTime is in seconds, there's no way it's ms. ```timestamp``` is the time of the latest refresh that happened from SPELL_DAMAGE just before. It should always be close to 0

2) Fixed that, hopefully the whole issue was caused by it

**Comment by wardz** [comment]
After some testing with the new changes it seems that when Winter's Chill resists it now has 0.30-0.42s delay between the events which is closer to the threshold indeed. (Again this is with 37 ping) So you might want to bump from 0.30s to 0.45s or something. 

However, when you resist WC on multiple targets it starts screwing up the timer again since the table only supports storing 1 WC timer at a time for the player:
https://github.com/rgd87/LibClassicDurations/blob/26823b1021d2ead8c6ebd94a5bfbd566da56df46/core.lua#L484-L488

This is not that big of a deal but thought I'd let u know.

![WoWScrnShot_040320_171940](https://user-images.githubusercontent.com/10900212/78379618-f4458480-75d2-11ea-95c4-25943e42302b.jpg)

**Comment by d87** [comment]
Right, added multitarget support now. And threshold to 0.5. Thanks

**Comment by wardz** [comment]
Great, seems to work all fine now.
